tablas =[
  {
    "NOMBRE_TABLA": "SP_APORTES_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_APORTES_BFV",
    "ORDEN": 3,
    "NOMBRE_COLUMNA": "TE_TIPO_APORTE",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_APORTES_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "MTO_APORTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 2,
    "NOMBRE_COLUMNA": "NUM_ENTIDAD",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 3
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "TE_PRIORIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 6,
    "NOMBRE_COLUMNA": "TE_SOLICITUD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 8,
    "NOMBRE_COLUMNA": "TE_PROPOSITO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 10,
    "NOMBRE_COLUMNA": "TE_POSTULACION",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 12,
    "NOMBRE_COLUMNA": "TE_PROGRAMA_FIN",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 16,
    "NOMBRE_COLUMNA": "TE_GARANTIA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 17,
    "NOMBRE_COLUMNA": "NUM_PROVINCIA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 18,
    "NOMBRE_COLUMNA": "NUM_CANTON",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 19,
    "NOMBRE_COLUMNA": "NUM_DISTRITO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 20,
    "NOMBRE_COLUMNA": "NUM_SOLICITUD",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 8
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 21,
    "NOMBRE_COLUMNA": "ID_PERSONA_CABEZA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 20
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 22,
    "NOMBRE_COLUMNA": "MTO_INGRESOS_NUCLEO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 24,
    "NOMBRE_COLUMNA": "MTO_DEUDAS_NUCLEO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 25,
    "NOMBRE_COLUMNA": "CE_APROBACION_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 26,
    "NOMBRE_COLUMNA": "ID_ESTRATO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 5
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 28,
    "NOMBRE_COLUMNA": "TE_INGENIERO_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 29,
    "NOMBRE_COLUMNA": "NUM_FUENTE_FONDO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 3
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 30,
    "NOMBRE_COLUMNA": "ID_INGENIERO_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 10
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 32,
    "NOMBRE_COLUMNA": "TE_CONTADOR_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 33,
    "NOMBRE_COLUMNA": "ID_CONTADOR_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 12
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 35,
    "NOMBRE_COLUMNA": "TE_ANALISTA_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 36,
    "NOMBRE_COLUMNA": "ID_ANALISTA_ENTIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 10
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 39,
    "NOMBRE_COLUMNA": "NUM_CASO_ANTERIOR",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 41,
    "NOMBRE_COLUMNA": "FEC_ANALISTA_ENTIDAD",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 42,
    "NOMBRE_COLUMNA": "FEC_FORMALIZACION_ENTIDAD",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 43,
    "NOMBRE_COLUMNA": "FEC_APROBACION_ENTIDAD",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 44,
    "NOMBRE_COLUMNA": "FEC_PRESENTACION_FORMALIZACION",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 45,
    "NOMBRE_COLUMNA": "FEC_FIRMA_SOLICITANTE",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 48,
    "NOMBRE_COLUMNA": "DES_DIRECCION_EXACTA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 100
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 50,
    "NOMBRE_COLUMNA": "NUM_PARAM",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 3
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 51,
    "NOMBRE_COLUMNA": "CANT_AULAS",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 52,
    "NOMBRE_COLUMNA": "MTO_GASTOS_PIA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 53,
    "NOMBRE_COLUMNA": "ESTADO_EXPEDIENTE",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 2
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 62,
    "NOMBRE_COLUMNA": "TE_ESTADO_CASO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CASOS_BFV",
    "ORDEN": 63,
    "NOMBRE_COLUMNA": "FEC_ESTADO_CASO",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "AREA_CONSTRUCCION",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 6,
    "NOMBRE_COLUMNA": "MTO_COSTO_METRO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 7,
    "NOMBRE_COLUMNA": "MTO_TASADO_CONSTRUCCION",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 8,
    "NOMBRE_COLUMNA": "MTO_VENTA_CONSTRUCCION",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 11,
    "NOMBRE_COLUMNA": "TE_RESPONSABLE_CIVIL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_CONSTRUCCION_BFV",
    "ORDEN": 12,
    "NOMBRE_COLUMNA": "ID_RESPONSABLE_CIVIL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 10
  },
  {
    "NOMBRE_TABLA": "SP_ESTADOS_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_ESTADOS_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "TE_ESTADO_CASO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_ESTADOS_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "FEC_ESTADO_CASO",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_GASTOS_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_GASTOS_BFV",
    "ORDEN": 3,
    "NOMBRE_COLUMNA": "TE_GASTO_CIERRE",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_GASTOS_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "MTO_GASTO_CIERRE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_GASTOS_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "IND_COSTEO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 2,
    "NOMBRE_COLUMNA": "ID_LOTE_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "TE_ESTADO_LOTE",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "NUM_FINCA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 8
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 6,
    "NOMBRE_COLUMNA": "NUM_TOMO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 8
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 7,
    "NOMBRE_COLUMNA": "NUM_FOLIO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 17
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 9,
    "NOMBRE_COLUMNA": "NUM_PROVINCIA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 10,
    "NOMBRE_COLUMNA": "NUM_CANTON",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 11,
    "NOMBRE_COLUMNA": "NUM_DISTRITO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 2
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 12,
    "NOMBRE_COLUMNA": "DES_DIRECCION_EXACTA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 100
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 13,
    "NOMBRE_COLUMNA": "NUM_LOTE",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 8
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 14,
    "NOMBRE_COLUMNA": "AREA_LOTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 15,
    "NOMBRE_COLUMNA": "MTO_COSTO_METRO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 16,
    "NOMBRE_COLUMNA": "MTO_VALOR_TASADO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 17,
    "NOMBRE_COLUMNA": "MTO_VALOR_VENTA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 18,
    "NOMBRE_COLUMNA": "NUM_PLANO_CATASTRO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 15
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 19,
    "NOMBRE_COLUMNA": "IND_CONSOLIDADO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_LOTE_BFV",
    "ORDEN": 20,
    "NOMBRE_COLUMNA": "ID_ART_10",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 2,
    "NOMBRE_COLUMNA": "ID_PERSONA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 20
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "TE_PARENTESCO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 6,
    "NOMBRE_COLUMNA": "TE_ESTADO_PERSONA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 7,
    "NOMBRE_COLUMNA": "ID_TIPO_DEUDOR",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 8,
    "NOMBRE_COLUMNA": "IND_IMPEDIMENTO_FISICO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 9,
    "NOMBRE_COLUMNA": "MTO_INGRESOS",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_NUCLEO_BFV",
    "ORDEN": 11,
    "NOMBRE_COLUMNA": "ID_POSEE_INGRESOS",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 1
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "NUM_CASO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 3,
    "NOMBRE_COLUMNA": "TE_PERIODICIDAD",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "TE_TIPO_CUOTA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 6,
    "NOMBRE_COLUMNA": "MTO_SOLUCION",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 7,
    "NOMBRE_COLUMNA": "PORC_CUOTA_INGRESO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 10
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 8,
    "NOMBRE_COLUMNA": "NUM_PLAZO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 3
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 9,
    "NOMBRE_COLUMNA": "NUM_TASA_INTERES",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 7
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 10,
    "NOMBRE_COLUMNA": "NUM_CUOTAS",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 4
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 11,
    "NOMBRE_COLUMNA": "MTO_CREDITO_BASE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 12,
    "NOMBRE_COLUMNA": "MTO_CUOTA_INICIAL",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 13,
    "NOMBRE_COLUMNA": "MTO_APORTE_CLIENTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 14,
    "NOMBRE_COLUMNA": "MTO_BONO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 15,
    "NOMBRE_COLUMNA": "MTO_GIRADO",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 16,
    "NOMBRE_COLUMNA": "MTO_REMANENTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 23,
    "NOMBRE_COLUMNA": "MTO_HIPOTECA",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_OPERACIONES_BFV",
    "ORDEN": 24,
    "NOMBRE_COLUMNA": "MTO_UTIL_REMANENTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 19
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 1,
    "NOMBRE_COLUMNA": "ID_PERSONA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 20
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 3,
    "NOMBRE_COLUMNA": "TE_IDENTIFICACION",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 5,
    "NOMBRE_COLUMNA": "TE_NIVEL_EDUCATIVO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 7,
    "NOMBRE_COLUMNA": "TE_GENERO",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 9,
    "NOMBRE_COLUMNA": "TE_ESTADO_CIVIL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 12,
    "NOMBRE_COLUMNA": "NOM_PERSONA",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 60
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 13,
    "NOMBRE_COLUMNA": "OBSERVACIONES",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 100
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 15,
    "NOMBRE_COLUMNA": "FEC_NACIMIENTO",
    "TIPO_DATA": "DATE",
    "TAMANIO": 7
  },
  {
    "NOMBRE_TABLA": "SP_PERSONAS_BFV",
    "ORDEN": 16,
    "NOMBRE_COLUMNA": "CODIGO_CLIENTE",
    "TIPO_DATA": "NUMBER",
    "TAMANIO": 22,
    "PRECISION": 12
  },
  {
    "NOMBRE_TABLA": "SP_PROFESIONALES_BFV",
    "ORDEN": 2,
    "NOMBRE_COLUMNA": "TE_PROFESIONAL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 6
  },
  {
    "NOMBRE_TABLA": "SP_PROFESIONALES_BFV",
    "ORDEN": 3,
    "NOMBRE_COLUMNA": "ID_PROFESIONAL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 10
  },
  {
    "NOMBRE_TABLA": "SP_PROFESIONALES_BFV",
    "ORDEN": 4,
    "NOMBRE_COLUMNA": "NOM_PROFESIONAL",
    "TIPO_DATA": "VARCHAR2",
    "TAMANIO": 60
  }
]

clientes = [
  {
    "CODIGO_CLIENTE": 2198694,
    "IDENTIFICACION": "207560245",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "MARIA   FERNANDA HERNANDEZ ROJAS",
    "FECHA_NACIMIENTO": "16081996"
  },
  {
    "CODIGO_CLIENTE": 2198757,
    "IDENTIFICACION": "111740850",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ALVARO   JOSE LORIA MADRIGAL",
    "FECHA_NACIMIENTO": "21061983"
  },
  {
    "CODIGO_CLIENTE": 2198786,
    "IDENTIFICACION": "111430599",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ALEJANDRO  LEPIZ SEGURA",
    "FECHA_NACIMIENTO": "19061982"
  },
  {
    "CODIGO_CLIENTE": 2198825,
    "IDENTIFICACION": "602140891",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "BELTRAN  BALTODANO RAMIREZ",
    "FECHA_NACIMIENTO": "19041968"
  },
  {
    "CODIGO_CLIENTE": 2198829,
    "IDENTIFICACION": "604170190",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "PABLO   STIWART BRICEÃ`O CALERO",
    "FECHA_NACIMIENTO": "24061994"
  },
  {
    "CODIGO_CLIENTE": 2198866,
    "IDENTIFICACION": "505200015",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "MATEO   KAHEL ESPINOZA FERNANDEZ",
    "FECHA_NACIMIENTO": "23052015"
  },
  {
    "CODIGO_CLIENTE": 2198750,
    "IDENTIFICACION": "108810535",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "MARCO   VINICIO CARRILLO AGUILAR",
    "FECHA_NACIMIENTO": "02061974"
  },
  {
    "CODIGO_CLIENTE": 2198766,
    "IDENTIFICACION": "115540026",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "MARIA   FERNANDA VALVERDE CHACON",
    "FECHA_NACIMIENTO": "04111993"
  },
  {
    "CODIGO_CLIENTE": 2198802,
    "IDENTIFICACION": "112270990",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "JENNY   PATRICIA AGUILAR ARAYA",
    "FECHA_NACIMIENTO": "06011985"
  },
  {
    "CODIGO_CLIENTE": 2198876,
    "IDENTIFICACION": "103260250",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "DEYANIRA  UMAÑA CHAVERRI",
    "FECHA_NACIMIENTO": "17102044"
  },
  {
    "CODIGO_CLIENTE": 2198700,
    "IDENTIFICACION": "120070504",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "BRIGITTE  SOLANO NAVARRO",
    "FECHA_NACIMIENTO": "23102007"
  },
  {
    "CODIGO_CLIENTE": 2198758,
    "IDENTIFICACION": "702320549",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "YERLIN   MILENY GUADAMUZ MENDEZ",
    "FECHA_NACIMIENTO": "05121994"
  },
  {
    "CODIGO_CLIENTE": 2198795,
    "IDENTIFICACION": "401850702",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ARLENY  ESPINOZA VILLEGAS",
    "FECHA_NACIMIENTO": "23041984"
  },
  {
    "CODIGO_CLIENTE": 2198858,
    "IDENTIFICACION": "605130699",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "AMY   TATIANA BARTELS GARCIA",
    "FECHA_NACIMIENTO": "28082008"
  },
  {
    "CODIGO_CLIENTE": 41,
    "IDENTIFICACION": "1234567890",
    "TIPO_PERSONA": "J",
    "NOMBRE": "   ",
    "FECHA_NACIMIENTO": "28082008"
  },
  {
    "CODIGO_CLIENTE": 2198697,
    "IDENTIFICACION": "117770578",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "GIMENA  MORA GONZALEZ",
    "FECHA_NACIMIENTO": "18052000"
  },
  {
    "CODIGO_CLIENTE": 2198745,
    "IDENTIFICACION": "116210557",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "VALERIA   PRISCILLA JIMENEZ CARVAJAL",
    "FECHA_NACIMIENTO": "08101995"
  },
  {
    "CODIGO_CLIENTE": 2198806,
    "IDENTIFICACION": "113270776",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "DIEGO   ARMANDO CHAVES MARQUEZ",
    "FECHA_NACIMIENTO": "19091987"
  },
  {
    "CODIGO_CLIENTE": 2198842,
    "IDENTIFICACION": "115670696",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "CHRISTEL   RAQUEL AGUERO BEITA",
    "FECHA_NACIMIENTO": "06031994"
  },
  {
    "CODIGO_CLIENTE": 2198846,
    "IDENTIFICACION": "112080469",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ALEJANDRA  BADILLA VARGAS",
    "FECHA_NACIMIENTO": "31051984"
  },
  {
    "CODIGO_CLIENTE": 2198871,
    "IDENTIFICACION": "121210741",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "FIORELLA  HIDALGO ESTRADA",
    "FECHA_NACIMIENTO": "04082011"
  },
  {
    "CODIGO_CLIENTE": 2198898,
    "IDENTIFICACION": "207320880",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ANTONIO   DE LOS ANGELES SOLANO MOREIRA",
    "FECHA_NACIMIENTO": "21111994"
  },
  {
    "CODIGO_CLIENTE": 2198691,
    "IDENTIFICACION": "121350883",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "CAMILA  ALVARADO QUIROS",
    "FECHA_NACIMIENTO": "21012012"
  },
  {
    "CODIGO_CLIENTE": 2198744,
    "IDENTIFICACION": "203930322",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "EDWIN   FRANCISCO RAMIREZ ALVARADO",
    "FECHA_NACIMIENTO": "08011964"
  },
  {
    "CODIGO_CLIENTE": 2198748,
    "IDENTIFICACION": "116670019",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "CAROLINA   GUISELLE QUIROS LOAIZA",
    "FECHA_NACIMIENTO": "03021997"
  },
  {
    "CODIGO_CLIENTE": 2198827,
    "IDENTIFICACION": "119850004",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ISAAC   JESUS ARAYA VARGAS",
    "FECHA_NACIMIENTO": "31122006"
  },
  {
    "CODIGO_CLIENTE": 2198698,
    "IDENTIFICACION": "116080545",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "RICARDO  ROSALES MONTERO",
    "FECHA_NACIMIENTO": "09061995"
  },
  {
    "CODIGO_CLIENTE": 2198702,
    "IDENTIFICACION": "115910790",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ANDRES   EDUARDO HIDALGO PICADO",
    "FECHA_NACIMIENTO": "13121994"
  },
  {
    "CODIGO_CLIENTE": 2198723,
    "IDENTIFICACION": "206580378",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "BRAYAN   ANTONIO LOZANO GUERRERO",
    "FECHA_NACIMIENTO": "11041989"
  },
  {
    "CODIGO_CLIENTE": 2198803,
    "IDENTIFICACION": "603940143",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "MANUEL  CUBERO MARTINEZ",
    "FECHA_NACIMIENTO": "23031991"
  },
  {
    "CODIGO_CLIENTE": 2198817,
    "IDENTIFICACION": "504090785",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ELIAS  MIRANDA VILLAGRA",
    "FECHA_NACIMIENTO": "25031996"
  },
  {
    "CODIGO_CLIENTE": 2198836,
    "IDENTIFICACION": "207270274",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "PAULINA  HUERTAS HIDALGO",
    "FECHA_NACIMIENTO": "29061994"
  },
  {
    "CODIGO_CLIENTE": 2198862,
    "IDENTIFICACION": "106810894",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ALBA   NIDIA VARGAS CHAVES",
    "FECHA_NACIMIENTO": "12121959"
  },
  {
    "CODIGO_CLIENTE": 40,
    "IDENTIFICACION": "112010101",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "FABIOLA  FALLAS FALLAS",
    "FECHA_NACIMIENTO": "25041990"
  },
  {
    "CODIGO_CLIENTE": 2198763,
    "IDENTIFICACION": "116140136",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "SERGIO   ADRIAN FERNANDEZ MURILLO",
    "FECHA_NACIMIENTO": "06081995"
  },
  {
    "CODIGO_CLIENTE": 2198838,
    "IDENTIFICACION": "604510439",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ADISSON   MARIELA ARIAS TORRES",
    "FECHA_NACIMIENTO": "02031999"
  },
  {
    "CODIGO_CLIENTE": 2198841,
    "IDENTIFICACION": "202870808",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ANALIVE  CAMBRONERO MORERA",
    "FECHA_NACIMIENTO": "14022026"
  },
  {
    "CODIGO_CLIENTE": 2198888,
    "IDENTIFICACION": "900730352",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "EMILIO  PALOMO CONTRERAS",
    "FECHA_NACIMIENTO": "02091963"
  },
  {
    "CODIGO_CLIENTE": 2198899,
    "IDENTIFICACION": "702510998",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "JOSHUA   ESTEBAN ROJAS ANGULO",
    "FECHA_NACIMIENTO": "26041997"
  },
  {
    "CODIGO_CLIENTE": 2198696,
    "IDENTIFICACION": "306450514",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "BIANCA   ISABELLA MARTINEZ OBANDO",
    "FECHA_NACIMIENTO": "29052018"
  },
  {
    "CODIGO_CLIENTE": 2198725,
    "IDENTIFICACION": "303220313",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ANA   LUCRECIA CALVO ARAYA",
    "FECHA_NACIMIENTO": "03111972"
  },
  {
    "CODIGO_CLIENTE": 2198779,
    "IDENTIFICACION": "501070984",
    "TIPO_PERSONA": "N",
    "SEXO": "M",
    "NOMBRE": "ALEJANDRINA  MATARRITA DIAZ",
    "FECHA_NACIMIENTO": "26112044"
  }
]
